import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowUpRight, BookOpen, BriefcaseBusiness, FileText, Globe2, Heart, MapPin, ShieldCheck, UsersRound } from 'lucide-react';
import { actions } from '@/lib/content';
import type { Article, Country, Project, SiteData } from '@/lib/site-data';
import { RecordExplorer } from './RecordExplorer';

type Lang = 'fr' | 'en' | 'es';
const link = (lang: Lang, route: string) => `/${lang}/${route}`;
const actionDetails: Record<string, { intro: string; points: [string,string][] }> = {
  education: { intro: 'PAAD agit pour une éducation accessible, de qualité et reliée aux perspectives d’avenir des jeunes.', points: [['Environnement scolaire', 'Améliorer les infrastructures, les équipements et les ressources d’apprentissage.'], ['Enseignants et élèves', 'Accompagner la formation des enseignants, les bourses et le soutien scolaire.'], ['Compétences d’avenir', 'Développer l’orientation, la formation professionnelle et les compétences numériques.']] },
  'developpement-economique': { intro: 'PAAD soutient les capacités économiques des personnes et des communautés pour créer des opportunités durables.', points: [['Entrepreneuriat et emploi', 'Renforcer les compétences entrepreneuriales, l’employabilité et l’accès au travail.'], ['Gestion et collectif', 'Développer l’éducation financière et soutenir les coopératives et organisations communautaires.'], ['Accès aux marchés', 'Faciliter la commercialisation et l’inclusion économique des femmes et des jeunes.']] },
};

function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="content-heading"><span className="content-eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state"><FileText size={30}/><h3>{title}</h3><p>{text}</p></div>; }
function Cta({ lang, title = 'Construisons la suite ensemble.' }: { lang: Lang; title?: string }) { return <div className="content-cta"><div><span>AGIR AVEC PAAD</span><h3>{title}</h3></div><Link className="button button-primary" href={link(lang,'contact')}>Prendre contact <ArrowRight size={17}/></Link></div>; }

export function PageBody({ lang, slug, data }: { lang: Lang; slug: string; data: SiteData }) {
  if (slug === 'nos-actions') return <><SectionTitle eyebrow="NOS PRIORITÉS" title="Deux priorités, une même ambition." text="L’éducation et le développement économique se renforcent mutuellement pour ouvrir des perspectives durables en Haïti."/><div className="editorial-grid">{actions.map((a,i)=><Link className="editorial-card" key={a.slug} href={link(lang,`actions/${a.slug}`)}><span>0{i+1}</span><h3>{a.title}</h3><p>{a.text}</p><ArrowUpRight size={20}/></Link>)}</div></>;
  if (slug.startsWith('actions/')) { const info = actionDetails[slug.split('/')[1]]; return <><SectionTitle eyebrow="NOTRE ACTION" title="Une démarche construite avec les acteurs locaux." text={info.intro}/><div className="feature-list">{info.points.map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><Cta lang={lang} title="Parlons de ce domaine d’action."/></>; }
  if (slug === 'qui-sommes-nous') return <><SectionTitle eyebrow="PAAD EN BREF" title="Une organisation indépendante, ancrée en Haïti." text="Fondé en 2024 par Renel Rosene, Renald Rosene et Esther Gladelle Toussaint, le Programme d’Actions et d’Aide pour le Développement est une organisation à but non lucratif basée à Port-au-Prince."/><div className="editorial-grid"><article className="editorial-card"><BookOpen size={26}/><h3>Éducation</h3><p>Améliorer l’accès à l’apprentissage, les ressources et les compétences utiles à l’avenir.</p></article><article className="editorial-card"><BriefcaseBusiness size={26}/><h3>Développement économique</h3><p>Soutenir l’entrepreneuriat, l’emploi et les initiatives collectives.</p></article></div><Cta lang={lang}/></>;
  if (slug === 'notre-histoire') return <><SectionTitle eyebrow="DEPUIS 2024" title="Trois fondateurs, une même conviction." text="Renel Rosene, Renald Rosene et Esther Gladelle Toussaint ont créé PAAD autour d’une idée simple : le développement durable se construit avec les Haïtiens, leurs initiatives et leurs compétences."/><div className="founders"><article><span>01</span><h3>Renel Rosene</h3><p>Cofondateur</p></article><article><span>02</span><h3>Renald Rosene</h3><p>Cofondateur</p></article><article><span>03</span><h3>Esther Gladelle Toussaint</h3><p>Cofondatrice</p></article></div><div className="quote-band">« Écouter avant de proposer. Construire avec, plutôt qu’imposer. »</div></>;
  if (slug === 'mission-vision') return <><SectionTitle eyebrow="MISSION & VISION" title="Éduquer. Créer des opportunités. Renforcer l’autonomie." text="PAAD renforce les capacités des personnes et des communautés par l’éducation et le développement économique."/><div className="split-editorial"><div><h3>Notre mission</h3><p>Développer l’accès à l’éducation, les compétences, l’entrepreneuriat et l’employabilité. Co-construire avec les communautés des initiatives qui favorisent les revenus et l’autonomie.</p></div><div><h3>Notre vision</h3><p>Un Haïti où chacun peut apprendre, entreprendre et participer pleinement au développement de sa communauté.</p></div></div><Cta lang={lang}/></>;
  if (slug === 'equipe') return <><SectionTitle eyebrow="COLLECTIF" title="Des membres impliqués dans la vie de PAAD." text="Les membres participent aux orientations, aux projets de terrain, à la logistique, à la communication et à la recherche de financements."/><div className="founders"><article><UsersRound size={27}/><h3>Les fondateurs</h3><p>Renel Rosene, Renald Rosene et Esther Gladelle Toussaint.</p></article><article><ShieldCheck size={27}/><h3>Le bureau</h3><p>Coordination des projets, administration, finances et relations avec les partenaires.</p></article><article><Heart size={27}/><h3>Les membres</h3><p>Un engagement actif dans la mise en œuvre et le suivi des actions.</p></article></div><Cta lang={lang} title="Rejoindre l’engagement de PAAD."/></>;
  if (slug === 'gouvernance') return <><SectionTitle eyebrow="RESPONSABILITÉ" title="Des décisions collégiales, une gestion documentée." text="Le bureau de PAAD définit les orientations, valide les projets et suit leur réalisation. Les décisions importantes sont discutées collectivement."/><div className="feature-list">{[['Indépendance','PAAD est une organisation à but non lucratif, sans affiliation partisane ou religieuse.'],['Traçabilité','Les dépenses et les décisions doivent pouvoir être documentées et expliquées.'],['Redevabilité','L’organisation rend compte de son action aux communautés, aux partenaires et aux donateurs.']].map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><Link className="text-link" href={link(lang,'rapports')}>Consulter les publications <ArrowUpRight size={18}/></Link></>;
  if (slug === 'valeurs') return <><SectionTitle eyebrow="NOS REPÈRES" title="Des principes qui engagent nos actions."/><div className="editorial-grid">{[['Intégrité','Agir avec honnêteté et cohérence.'],['Transparence','Expliquer les décisions et l’utilisation des ressources.'],['Respect','Reconnaître la dignité et les choix de chaque personne.'],['Solidarité','Construire des réponses collectives.'],['Efficacité','Évaluer les effets réels des actions.'],['Responsabilité','Rendre compte aux communautés et aux partenaires.']].map(([title,text],i)=><article className="editorial-card" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></>;
  if (slug === 'projets') { const projects=data.projects.filter(p=>p.published); return <><SectionTitle eyebrow="NOS PROJETS" title="Suivre les initiatives du terrain." text="Chaque fiche présente son lieu, son domaine, son état d’avancement et les informations vérifiées par PAAD."/>{projects.length ? <RecordExplorer kind="projects" records={projects} lang={lang}/> : <Empty title="Les fiches projets arrivent bientôt." text="PAAD publiera ses projets après vérification des lieux, des partenaires, des étapes et des résultats."/>}</>; }
  if (slug === 'pays') { const countries=data.countries.filter(c=>c.published); return <><SectionTitle eyebrow="OÙ NOUS AGISSONS" title="Une présence fondée sur l’ancrage local." text="Découvrez les territoires pour lesquels PAAD dispose d’informations confirmées."/><div className="country-list">{countries.map(c=><Link key={c.slug} href={link(lang,`pays/${c.slug}`)}><Globe2 size={28}/><div><span>PAYS D’INTERVENTION</span><h3>{c.name}</h3><p>{c.summary}</p></div><ArrowUpRight size={22}/></Link>)}</div>{!countries.length&&<Empty title="Les pays seront annoncés ici." text="Les implantations seront affichées après confirmation par PAAD."/>}</>; }
  if (slug === 'impact') { const metrics=data.metrics.filter(m=>m.published); return <><SectionTitle eyebrow="NOTRE IMPACT" title="Mesurer, comprendre, progresser." text="PAAD définit des indicateurs pour ses deux priorités et publie uniquement des résultats vérifiés, avec leur source et leur méthode de calcul."/>{metrics.length>0&&<div className="metrics-grid">{metrics.map((m,i)=><article key={i}><strong>{m.value}</strong><h3>{m.label}</h3><small>Source : {m.source}</small></article>)}</div>}<div className="feature-list">{[['Éducation','Suivre l’accès à l’apprentissage, les ressources, la formation et les parcours des apprenants.'],['Développement économique','Suivre les compétences acquises, l’emploi, les initiatives créées et l’accès aux marchés.'],['Apprentissage collectif','Recueillir les retours des communautés et ajuster les actions selon les résultats.']].map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div>{!metrics.length&&<p className="data-note">Les chiffres seront affichés après validation des données et de leurs sources.</p>}</>; }
  if (slug === 'histoires') { const stories=data.stories.filter(s=>s.published); return <><SectionTitle eyebrow="PAROLES DE TERRAIN" title="Des histoires racontées avec consentement." text="Les personnes concernées participent au choix de leurs mots et à la manière dont leurs parcours sont présentés."/>{stories.length?<div className="story-grid">{stories.map((s,i)=><blockquote key={i}>« {s.quote} »<footer><strong>{s.name}</strong><span>{s.place} · {s.programme}</span></footer></blockquote>)}</div>:<Empty title="Les témoignages seront publiés ici." text="PAAD recueillera les accords nécessaires avant toute publication."/>}</>; }
  if (slug === 'rapports') { const reports=data.reports.filter(r=>r.published); return <><SectionTitle eyebrow="TRANSPARENCE" title="Documents et rapports accessibles." text="Cette bibliothèque rassemblera les rapports annuels, financiers, d’impact et les documents institutionnels de PAAD."/><div className="report-categories">{['Rapports annuels','Rapports d’impact','Rapports financiers','Documents institutionnels'].map(t=><div key={t}><FileText size={25}/><h3>{t}</h3></div>)}</div>{reports.length?<div className="report-list">{reports.map((r,i)=><a key={i} href={r.url} target="_blank" rel="noopener noreferrer"><span>{r.type} · {r.year}</span><strong>{r.title}</strong><ArrowUpRight size={20}/></a>)}</div>:<Empty title="Aucun rapport public pour le moment." text="Les documents officiels seront ajoutés dès leur validation."/>}</>; }
  if (['actualites','communiques','evenements'].includes(slug)) { const category=slug==='communiques'?'Communiqué':slug==='evenements'?'Événement':null;const articles=data.articles.filter(a=>a.published&&(!category||a.category===category));return <><SectionTitle eyebrow="À LA UNE" title={slug==='actualites'?'Les nouvelles de PAAD.':slug==='communiques'?'Les communiqués officiels.':'Nos événements.'} text="Les publications sont datées et vérifiées par l’équipe PAAD."/>{articles.length?<RecordExplorer kind="articles" records={articles} lang={lang}/>:<Empty title="Les publications arrivent bientôt." text="Cette rubrique sera mise à jour par l’équipe PAAD."/>}</>; }
  if (slug === 'partenaires') { const partners=data.partners.filter(p=>p.published);return <><SectionTitle eyebrow="COOPÉRATION" title="Ils agissent avec nous." text="Nous construisons des collaborations fondées sur des objectifs partagés, une répartition claire des rôles et la transparence."/>{partners.length?<div className="partner-grid">{partners.map((p,i)=><a key={i} href={p.url||'#'} target={p.url?'_blank':undefined} rel="noopener noreferrer">{p.logo?<Image src={p.logo} alt={p.name} width={160} height={80}/>:p.name}</a>)}</div>:<Empty title="Les partenaires seront présentés ici." text="Leurs noms et logos seront publiés avec leur accord."/>}<Cta lang={lang} title="Devenir partenaire de PAAD."/></>; }
  if (slug === 'faq') return <><SectionTitle eyebrow="QUESTIONS FRÉQUENTES" title="L’essentiel en quelques réponses."/><div className="faq-list"><details><summary>Où agit PAAD ?</summary><p>PAAD est basé à Port-au-Prince et mène son action en Haïti. Les territoires précis sont détaillés lorsqu’un projet est publié.</p></details><details><summary>Quels sont ses domaines prioritaires ?</summary><p>L’éducation et le développement économique sont les deux priorités stratégiques de PAAD.</p></details><details><summary>Comment proposer un partenariat ?</summary><p>La page « Devenir partenaire » permet de préparer un message à l’équipe PAAD.</p></details><details><summary>Peut-on faire un don en ligne ?</summary><p>Le paiement en ligne sera disponible une fois le dispositif de collecte officiel activé.</p></details><details><summary>Où trouver les rapports ?</summary><p>Les documents validés seront publiés dans la rubrique « Rapports ».</p></details></div></>;
  if (['mentions-legales','confidentialite','cookies','conditions-de-don'].includes(slug)) return <><SectionTitle eyebrow="INFORMATIONS" title="Informations en cours de validation." text="Cette page sera complétée avec les éléments juridiques officiels avant la mise en ligne publique."/><div className="legal-note"><ShieldCheck size={30}/><p>{slug==='cookies'?'Aucun service de suivi publicitaire ou analytique n’est actuellement activé.':slug==='conditions-de-don'?'Aucun paiement n’est actuellement collecté par ce site.':'Les mentions obligatoires seront renseignées après confirmation par PAAD.'}</p></div></>;
  return null;
}

export function RecordPage({ lang, kind, record }: { lang: Lang; kind: 'project'|'country'|'article'; record: Project|Country|Article }) {
  const isProject=kind==='project'; const isCountry=kind==='country';
  const back=isProject?'projets':isCountry?'pays':'actualites';
  const title='title' in record?record.title:record.name;
  const summary=record.summary;
  const body=record.body;
  const image=isProject?(record as Project).image:!isCountry?(record as Article).image:undefined;
  return <><div className="record-hero"><div className="wrap"><Link href={link(lang,back)} className="record-back">← Retour à {back}</Link><span>{isProject?(record as Project).domain:isCountry?'PAYS D’INTERVENTION':(record as Article).category}</span><h1>{title}</h1><p>{summary}</p></div></div>{image&&<div className="record-cover"><Image src={image} alt="" fill sizes="100vw"/></div>}<div className="wrap record-detail"><main><div className="record-prose">{body.split(/\n\n+/).map((p,i)=><p key={i}>{p}</p>)}</div>{isCountry&&<><h2>Domaines d’intervention</h2><div className="domain-tags">{(record as Country).domains.map(d=><span key={d}>{d}</span>)}</div></>}{isProject&&<><h2>Repères du projet</h2><div className="record-facts"><span>Lieu <strong>{(record as Project).region}, {(record as Project).country}</strong></span><span>Statut <strong>{(record as Project).status}</strong></span><span>Domaine <strong>{(record as Project).domain}</strong></span></div></>}</main><aside><MapPin size={24}/><h3>{isCountry?'PAAD sur le terrain':'En savoir plus'}</h3><p>{isCountry?'Les projets détaillés seront reliés à ce pays après leur publication.':'Pour connaître les partenaires et les prochaines étapes, contactez PAAD.'}</p><Link className="button button-primary" href={link(lang,'contact')}>Contacter PAAD <ArrowRight size={16}/></Link></aside></div></>;
}
